{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cq-postgres
spec:
  selector:
    app: cq-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
{{- end }}
